image: node:15.6

stages:
  - install_dependencies
  - test
  - build

install:dependencies:
    stage: install_dependencies
    script:
        - npm i
    cache:
        key: ${CI_COMMIT_BRANCH}
        paths:
            - node_modules

ESLinter:
    stage: test
    dependencies:
        - install:dependencies
    script:
        - node ./node_modules/eslint/bin/eslint.js src/


Build Nitro:
  stage: build
  dependencies:
      - install:dependencies
  script:
    - npm i
    - cp src/index.html.example src/index.html
    - cp src/configuration.json.example src/configuration.json
    - npm run build-prod
  cache:
    key: ${CI_COMMIT_BRANCH}
    paths:
      - node_modules
  artifacts:
    expire_in: 2 weeks
    paths:
      - dist/*
